local config = {
  cmd = {
    vim.fn.executable('OmniSharp') == 1 and 'OmniSharp' or 'omnisharp',
  },
  enable_import_completion = true,
  -- enable_roslyn_analyzers = true, commented out waiting to get correct optionts configured
  enable_analyzer_support = true,
  enable_decompilation_support = true,
  organize_imports_on_format = true,
  inlay_hints_options = {
    enable_for_parameters = true,
    for_literal_parameters = true,
    for_indexer_parameters = true,
    for_object_creation_parameters = true,
    for_other_parameters = true,
    suppress_for_parameters_that_differ_only_by_suffix = false,
    suppress_for_parameters_that_match_method_intent = false,
    suppress_for_parameters_that_match_argument_name = false,
    enable_for_types = true,
    for_implicit_variable_types = true,
    for_lambda_parameter_types = true,
    for_implicit_object_creation = true,
  },
  handlers = {
    ["textDocument/definition"] = require("omnisharp_extended").handler,
  },
  extra_on_attach = function(client, _)
    client.server_capabilities.semanticTokensProvider = {
      full = vim.empty_dict(),
      legend = {
        tokenModifiers = { "static_symbol" },
        tokenTypes = {
          "comment",
          "excluded_code",
          "identifier",
          "keyword",
          "keyword_control",
          "number",
          "operator",
          "operator_overloaded",
          "preprocessor_keyword",
          "string",
          "whitespace",
          "text",
          "static_symbol",
          "preprocessor_text",
          "punctuation",
          "string_verbatim",
          "string_escape_character",
          "class_name",
          "delegate_name",
          "enum_name",
          "interface_name",
          "module_name",
          "struct_name",
          "type_parameter_name",
          "field_name",
          "enum_member_name",
          "constant_name",
          "local_name",
          "parameter_name",
          "method_name",
          "extension_method_name",
          "property_name",
          "event_name",
          "namespace_name",
          "label_name",
          "xml_doc_comment_attribute_name",
          "xml_doc_comment_attribute_quotes",
          "xml_doc_comment_attribute_value",
          "xml_doc_comment_cdata_section",
          "xml_doc_comment_comment",
          "xml_doc_comment_delimiter",
          "xml_doc_comment_entity_reference",
          "xml_doc_comment_name",
          "xml_doc_comment_processing_instruction",
          "xml_doc_comment_text",
          "xml_literal_attribute_name",
          "xml_literal_attribute_quotes",
          "xml_literal_attribute_value",
          "xml_literal_cdata_section",
          "xml_literal_comment",
          "xml_literal_delimiter",
          "xml_literal_embedded_expression",
          "xml_literal_entity_reference",
          "xml_literal_name",
          "xml_literal_processing_instruction",
          "xml_literal_text",
          "regex_comment",
          "regex_character_class",
          "regex_anchor",
          "regex_quantifier",
          "regex_grouping",
          "regex_alternation",
          "regex_text",
          "regex_self_escaped_character",
          "regex_other_escape",
        },
      },
      range = true,
    }
  end,
}
return config
